name: model_soups
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - astroid
  - blas
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi
  - cudatoolkit
  - dataclasses
  - freetype
  - intel-openmp
  - isort
  - jpeg
  - lazy-object-proxy
  - lcms2
  - ld_impl_linux-64
  - libffi
  - libgcc-ng
  - libpng
  - libstdcxx-ng
  - libtiff
  - libuv
  - libwebp-base
  - lz4-c
  - mccabe
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - ninja
  - ninja-base
  - numpy
  - numpy-base
  - olefile
  - openjpeg
  - openssl
  - pillow
  - pip
  - pylint
  - python>=3.11
  - pytorch>=2.6.0
  - pytorch-cuda>=12.1
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - toml
  - torchvision
  - typed-ast
  - typing-extensions
  - typing_extensions
  - wheel=0.37.1=pyhd3eb1b0_0
  - wrapt
  - xz
  - zlib
  - zstd
  - pip:
    - charset-normalizer
    - cycler
    - ftfy
    - idna
    - importlib-resources
    - kiwisolver
    - matplotlib
    - pandas
    - pyparsing
    - python-dateutil
    - pytz
    - regex
    - requests
    - tqdm
    - urllib3
    - wcwidth
    - wget
    - zipp
prefix: /home/mitchnw/anaconda3/envs/model_soups

